---
title: "R Notebook"
authors: Maciej Mionskowski, Tomasz Zawadzki
output: html_notebook
---

```{r}
install.packages("dplyr")
install.packages("rjson")
install.packages("devtools")
install.packages("ggplot2")
```

```{r}
library(dplyr)
```

```{r}
library(devtools)
devtools::install_github('cttobin/ggthemr')
```

```{r}
library(ggplot2)
#library(ggthemr)
#ggthemr('flat', layout = 'scientific')
```

```{r}
delays_csv <- read.csv('csv/norm3.csv')
delays <- delays_csv %>%
  transform(delays_csv,
    delay = delay/60,
    day = as.Date(day),
    theoretical_time = as.difftime(as.character(theoretical_time), "%H:%M:%S", units="hours")
  ) %>% filter(abs(delay) < 4*60)
delays$weekday <- weekdays(as.Date(delays$day))
```

```{r}
summary(delays$delay)
```

```{r} 
df <- data.frame(delay = delays$delay) %>% filter(delay >= -10 & delay <= 30)
ggplot(df, aes(x=delay, y=..density..)) +
  geom_histogram(binwidth=1) +
  labs(title="Histogram opóźnień przyjazdów na przystanek", x="Czas [min]", y=element_blank()) +
  scale_y_continuous(labels=scales::percent, limits=c(0, 0.25))
```

```{r}
df <- delays %>% distinct(trip, weekday) %>% group_by(weekday) %>% count()
ggplot(df, aes(x=weekday, y=n)) + 
  geom_bar(stat="identity", width=0.5) +
  labs(title="Rozkład kursów według dnia tygodnia", x="Dzień tygodnia", y="Liczba kursów") +
  scale_x_discrete(limits=c("poniedziałek", "wtorek", "środa", "czwartek", "piątek", "sobota", "niedziela"))
```

```{r}
df <- delays %>% distinct(trip, weekday) %>% group_by(weekday) %>% count()
ggplot(df, aes(x=weekday, y=n)) + 
  geom_bar(stat="identity", width=0.5) +
  labs(title="Rozkład kursów według dnia tygodnia", x="Dzień tygodnia", y="Liczba kursów") +
  scale_x_discrete(limits=c("poniedziałek", "wtorek", "środa", "czwartek", "piątek", "sobota", "niedziela"))
```

```{r}
breaks <- 0:12*2
ggplot(delays, aes(x=theoretical_time)) +
  geom_histogram(binwidth=0.25) +
  labs(title="Rozkład kursów według godziny", x="Godzina", y="Liczba kursów") +
  scale_x_continuous(
    breaks=breaks,
    labels=paste(breaks, ":00", sep="")
  )
```



