---
title: "R Notebook"
authors: Maciej Mionskowski, Tomasz Zawadzki
output: html_notebook
---

```{r}
install.packages("dplyr")
install.packages("rjson")
install.packages("devtools")
install.packages("ggplot2")
install.packages("devtools")
library(devtools)
devtools::install_github('cttobin/ggthemr')
```

```{sql}
SELECT trip, stop_id, trip_id, vehicle_id, theoretical_time, route_id, (SELECT delay_in_seconds FROM matdel as sub WHERE sub.trip = matdel.trip AND sub.stop_id = matdel.stop_id ORDER BY last_update DESC LIMIT 1) as delay, DATE(last_update) as day FROM matdel GROUP BY trip, stop_id, trip_id, vehicle_id, theoretical_time, route_id, DATE(last_update);
```

```{r}
library(dplyr)
library(ggplot2)
library(ggthemr)
ggthemr('flat', layout = 'scientific')
Sys.setenv(LANG = "pl")
Sys.setlocale('LC_TIME','pl_PL.UTF-8')
```

```{r}
delays_csv <- read.csv('csv/norm.csv')
delays <- delays_csv %>%
  transform(delays_csv,
    delay = delay/60,
    day = as.Date(day),
    theoretical_time = as.difftime(as.character(theoretical_time), "%H:%M:%S", units="hours")
  ) %>% filter(abs(delay) < 4*60)
delays$weekday <- (as.POSIXlt(as.Date(delays$day))$wday - 1) %% 7 + 1
```

```{r}
library(rjson)
raw_stops <- fromJSON(file='csv/stops.json')
stops <- raw_stops[['2019-06-20']][['stops']]
stops <- lapply(stops, function(x) {
  x[sapply(x, is.null)] <- NA
  unlist(x)
})
stops <- data.frame(do.call("rbind", stops))
```

```{r}
raw_routes <- fromJSON(file='csv/routes.json')
routes <- raw_routes[['2019-06-20']][['routes']]
routes <- lapply(routes, function(x) {
  x[sapply(x, is.null)] <- NA
  unlist(x)
})
routes <- data.frame(do.call("rbind", routes))
```

```{r}
stops_in_trip <- fromJSON(file='csv/stopsintrips.json')
stops_in_trip <- stops_in_trip[['2019-06-20']][['stopsInTrip']]
stops_in_trip <- lapply(stops_in_trip, function(x) {
  x[sapply(x, is.null)] <- NA
  unlist(x)
})
stops_in_trip <- data.frame(do.call("rbind", stops_in_trip))
stop_delays <- merge(x=delays, y=stops_in_trip, by.x=c("trip_id", "route_id", "stop_id"), by.y=c("tripId", "routeId", "stopId"))
stop_delays <- merge(stop_delays, stops, by.x="stop_id", by.y="stopId")
stop_delays$stopSequence = as.numeric(as.character(stop_delays$stopSequence))
#stop_delays$stopName <- reorder(stop_delays$stopName, stop_delays$stopSequence)
```

```{r}
summary(delays$delay)
```

```{r} 
df <- data.frame(delay = delays$delay) %>% filter(delay >= -10 & delay <= 30)
ggplot(df, aes(x=delay, y=..density..)) +
  geom_histogram(binwidth=1) +
  labs(title="Histogram opóźnień przyjazdów na przystanek", x="Czas [min]", y=element_blank()) +
  scale_y_continuous(labels=scales::percent, limits=c(0, 0.25))
```

```{r}
df <- delays %>% distinct(trip, weekday) %>% group_by(weekday) %>% count()
ggplot(df, aes(x=weekday, y=n)) + 
  geom_bar(stat="identity", width=0.5) +
  labs(title="Rozkład kursów według dnia tygodnia", x="Dzień tygodnia", y="Liczba kursów") +
  scale_x_continuous(
    breaks=1:7,
    labels=c("poniedziałek", "wtorek", "środa", "czwartek", "piątek", "sobota", "niedziela"))
```


```{r}
breaks <- 0:12*2
ggplot(delays %>% filter(!weekday %in% c(6,7)), aes(x=theoretical_time)) +
  geom_histogram(binwidth=0.25) +
  labs(title="Rozkład kursów według godziny w dni robocze", x="Godzina", y="Liczba kursów") +
  scale_x_continuous(
    breaks=breaks,
    labels=paste(breaks, "00", sep=":")
  )
```

```{r}
breaks <- 0:12*2
ggplot(delays %>% filter(weekday %in% c(6,7)), aes(x=theoretical_time)) +
  geom_histogram(binwidth=1/4) +
  labs(title="Rozkład kursów według godziny w dni weekendy", x="Godzina", y="Liczba kursów") +
  scale_x_continuous(
    breaks=breaks,
    labels=paste(breaks, "00", sep=":")
  )
```

```{r}
ticks <- 0:12*2
ggplot(delays, aes(x = theoretical_time, y = delay)) +
  stat_summary_bin(fun.y="mean", geom="bar", binwidth=1) +
  labs(title="Spóźnienie według godziny", x="Godzina", y="Średnie opóźnienie [min]") +
  scale_x_continuous(
    breaks=ticks,
    labels=paste(ticks, "00", sep=":")
  ) 
```

```{r}
ticks <- 0:12*2
ggplot(delays, aes(x = theoretical_time, y = delay)) +
  stat_summary(fun.y="mean") +
  geom_smooth() +
  labs(title="Spóźnienie według godziny", x="Godzina", y="Średnie opóźnienie [min]") +
  scale_x_continuous(
    breaks=ticks,
    labels=paste(ticks, "00", sep=":")
  ) +
  coord_cartesian(ylim=c(0, 6))
```

```{r}
breaks <- 0:24
ggplot(delays, aes(x=theoretical_time, y=delay)) +
  stat_summary(fun.y="mean", geom="bar") +
  labs(title="Rozkład kursów według godziny", x="Godzina", y="Liczba kursów") +
  scale_x_continuous(
    breaks=breaks,
    labels=paste(breaks, "00", sep=":")
  )
```

```{r}
avgs <- delays %>%
	group_by(stop_id) %>%
	summarise(mean = mean(delay), length = length(delay)) %>%
  filter(length > 20) %>%
  arrange(-mean)
avgs
```

```{r}
line_df <- stop_delays %>% filter(route_id == 2 & trip_id == 12)
ggplot(line_df, aes(as.character(stopSequence), delay)) +
  geom_point(alpha = 0.2) +
  labs(title="Rozkład spóźnienia linii tramwajowej nr 2 na kolejnych przystankach", y="Opóźnienie", x = "Przystanek") +
  scale_x_discrete(limits= line_df %>% distinct(stopSequence) %>% arrange(stopSequence) %>% `$`(stopSequence) %>% as.character, labels=line_df %>% distinct(stopSequence, stopName) %>% arrange(stopSequence) %>% `$`(stopName)) + 
   theme(axis.text.x = element_text(angle = 90, hjust = 1, margin = margin(0, 0, 0, -1))) +
  
  coord_cartesian(ylim = c(-10:30))
```

```{r}
avgDelay <- line_df %>% group_by(stopSequence, floor(theoretical_time)) %>% mutate(avg_delay = mean(delay)) %>% ungroup() %>% distinct(stopSequence, theoretical_time, avg_delay, stopName) %>% arrange(stopSequence)
ggplot(avgDelay, aes(stopName, as.integer(theoretical_time))) + coord_flip() + geom_tile(aes(fill = avg_delay), colour = "white") +
scale_fill_gradient(low = "white", high = "steelblue")
```

```{r}
ggplot(delays %>% filter(delay >= -5 & delay <= 10 & route_id == 2), aes(x=stop_id, y=delay) ) +
  stat_density_2d(aes(fill = ..density..), geom = "raster", contour = FALSE)
delays
```